### ISSUE TITLE
Cursor position is not correctly displayed with DPI scaling or zoom

### ISSUE THREAD

**Issue by RunDevelopment** [rulex-rs/playground#4]
When the playground is zoomed in, either because of system DPI scaling or browser zoom, the cursor is not displayed in the correct position. This also affects ranges shown as selected.

In this example, the characters `ef"]` are selected.
![image](https://user-images.githubusercontent.com/20878432/210134527-b0c4f657-3d3e-419d-8806-bdfd14e3ea18.png)
Here is me deleting the selected characters
![image](https://user-images.githubusercontent.com/20878432/210134565-42e517cf-d165-4e19-8661-5767663169a5.png)

When I set the browser zoom to 80% to cancel out my 125% DPI scaling, the cursor and selections are displayed correctly:
![image](https://user-images.githubusercontent.com/20878432/210134592-d4644371-771b-438c-a0a3-e1b1b20ee8f9.png)

**Comment by Aloso** [comment]
I'm aware of this bug, and it's quite annoying. It seems to be caused by monaco-editor, since I've observed the same bug on a few other pages as well. Confusingly, I only have this bug on mobile, and not in Chrome or Firefox on my Linux laptop.

EDIT: I just found a solution on StackOverflow and deployed a fix. Can you confirm that it works now?
